---
apiVersion: v1
kind: Service
metadata:
  name: capstone-project
spec:
  type: LoadBalancer
  selector:
    app: capstone-project
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
