apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-project
  template:
    metadata:
      labels:
        app: capstone-project
    spec:
      containers:
        - name: capstone-project
          image: kusumass/capstone-project-webapp:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%

